### ISSUE TITLE
CI error: "very step must define a `uses` or `run` key"

### ISSUE THREAD

**Issue by gr2m** [open-sauced/goals-template#5]
See https://github.com/gr2m/open-sauced-goals/actions/runs/135354046

Problem is the first step, it only has the `name` property

https://github.com/open-sauced/goals-template/blob/ec1ca18f6791322267c680f854c9143fb59d9b32/.github/workflows/sync-2-upstream.yml#L1-L19

**Comment by bdougie** [comment]
Ah, good catch. I think this is probably what @ryanwarnercodes was seeing as well.

**Comment by bdougie** [comment]
fixed in #6
